# Generated by Django 6.1.1 on 2026-09-10 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='نام کاربر')),
                ('name_fa', models.CharField(max_length=120, null=True, verbose_name='نام کاربر')),
                ('name_en', models.CharField(max_length=120, null=True, verbose_name='نام کاربر')),
                ('name_ar', models.CharField(max_length=120, null=True, verbose_name='نام کاربر')),
                ('gender', models.CharField(choices=[('male', 'آقا'), ('female', 'خانم')], default='male', max_length=10, verbose_name='جنسیت')),
                ('project_topic', models.CharField(max_length=200, verbose_name='موضوع پروژه')),
                ('project_topic_fa', models.CharField(max_length=200, null=True, verbose_name='موضوع پروژه')),
                ('project_topic_en', models.CharField(max_length=200, null=True, verbose_name='موضوع پروژه')),
                ('project_topic_ar', models.CharField(max_length=200, null=True, verbose_name='موضوع پروژه')),
                ('comment', models.TextField(verbose_name='نظر')),
                ('comment_fa', models.TextField(null=True, verbose_name='نظر')),
                ('comment_en', models.TextField(null=True, verbose_name='نظر')),
                ('comment_ar', models.TextField(null=True, verbose_name='نظر')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'نظر کاربر',
                'verbose_name_plural': 'نظرات کاربران',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
