# Generated by Django 6.1 on 2026-08-30 12:59

import ckeditor.fields
import django.db.models.deletion
import meta.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='نام')),
                ('name_fa', models.CharField(max_length=80, null=True, verbose_name='نام')),
                ('name_en', models.CharField(max_length=80, null=True, verbose_name='نام')),
                ('name_ar', models.CharField(max_length=80, null=True, verbose_name='نام')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='توضیح')),
                ('description_fa', models.TextField(blank=True, null=True, verbose_name='توضیح')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='توضیح')),
                ('description_ar', models.TextField(blank=True, null=True, verbose_name='توضیح')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('name_fa', models.CharField(max_length=50, null=True, verbose_name='نام')),
                ('name_en', models.CharField(max_length=50, null=True, verbose_name='نام')),
                ('name_ar', models.CharField(max_length=50, null=True, verbose_name='نام')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'تگ',
                'verbose_name_plural': 'تگ\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('title_fa', models.CharField(max_length=200, null=True, verbose_name='عنوان')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='عنوان')),
                ('title_ar', models.CharField(max_length=200, null=True, verbose_name='عنوان')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('excerpt', models.TextField(blank=True, max_length=300, verbose_name='خلاصه')),
                ('excerpt_fa', models.TextField(blank=True, max_length=300, null=True, verbose_name='خلاصه')),
                ('excerpt_en', models.TextField(blank=True, max_length=300, null=True, verbose_name='خلاصه')),
                ('excerpt_ar', models.TextField(blank=True, max_length=300, null=True, verbose_name='خلاصه')),
                ('body', ckeditor.fields.RichTextField(verbose_name='متن')),
                ('body_fa', ckeditor.fields.RichTextField(null=True, verbose_name='متن')),
                ('body_en', ckeditor.fields.RichTextField(null=True, verbose_name='متن')),
                ('body_ar', ckeditor.fields.RichTextField(null=True, verbose_name='متن')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='تصویر کاور')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('published', 'منتشر شده')], default='draft', max_length=12, verbose_name='وضعیت')),
                ('is_featured', models.BooleanField(default=False, verbose_name='ویژه')),
                ('meta_title', models.CharField(blank=True, max_length=70, verbose_name='عنوان SEO')),
                ('meta_title_fa', models.CharField(blank=True, max_length=70, null=True, verbose_name='عنوان SEO')),
                ('meta_title_en', models.CharField(blank=True, max_length=70, null=True, verbose_name='عنوان SEO')),
                ('meta_title_ar', models.CharField(blank=True, max_length=70, null=True, verbose_name='عنوان SEO')),
                ('meta_description', models.TextField(blank=True, max_length=160, verbose_name='توضیح SEO')),
                ('meta_description_fa', models.TextField(blank=True, max_length=160, null=True, verbose_name='توضیح SEO')),
                ('meta_description_en', models.TextField(blank=True, max_length=160, null=True, verbose_name='توضیح SEO')),
                ('meta_description_ar', models.TextField(blank=True, max_length=160, null=True, verbose_name='توضیح SEO')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, verbose_name='کلمات کلیدی')),
                ('meta_keywords_fa', models.CharField(blank=True, max_length=255, null=True, verbose_name='کلمات کلیدی')),
                ('meta_keywords_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='کلمات کلیدی')),
                ('meta_keywords_ar', models.CharField(blank=True, max_length=255, null=True, verbose_name='کلمات کلیدی')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انتشار')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('views', models.PositiveIntegerField(default=0, verbose_name='بازدید')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.category', verbose_name='دسته\u200cبندی')),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='blog.tag', verbose_name='تگ\u200cها')),
            ],
            options={
                'verbose_name': 'پست',
                'verbose_name_plural': 'پست\u200cها',
                'ordering': ['-published_at', '-created_at'],
            },
            bases=(meta.models.ModelMeta, models.Model),
        ),
    ]
